apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mlebrazi-lol-tls
spec:
  secretName: mlebrazi-lol
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: mlebrazi.lol
  dnsNames:
    - mlebrazi.lol
    - www.mlebrazi.lol
  acme:
    config:
      - http01:
          ingressClass: nginx
          domains:
            - mlebrazi.lol
            - www.mlebrazi.lol