version: "3"
services:
    # Database
    postgres:
        image: "postgres:latest"
        environment:
            - POSTGRES_PASSWORD=postgres_password
    # Cache
    redis:
        image: "redis:latest"
    # Router
    nginx:
        depends_on:
            - api
            - client
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - "3050:80"
    # API Server
    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
        volumes:
            - /home/node/app/node_modules
            - ./server:/home/node/app
    # Client
    client:
        environment:
            - WDS_SOCKET_PORT=0
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - /home/node/app/node_modules
            - ./client:/home/node/app
    # Worker
    worker:
        build:
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes:
            - /home/node/app/node_modules
            - ./worker:/home/node/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
