version: "3"
services:
    client:
        image: "lmachraf/fib-client-prod"
        mem_limit: 128m
        hostname: client
    server:
        image: "lmachraf/fib-server-prod"
        mem_limit: 128m
        hostname: api
        environment:
            - REDIS_HOST=$REDIS_HOST
            - REDIS_PORT=$REDIS_PORT
            - PGUSER=$PGUSER
            - PGHOST=$PGHOST
            - PGDATABASE=$PGDATABASE
            - PGPASSWORD=$PGPASSWORD
            - PGPORT=$PGPORT
    worker:
        image: "lmachraf/fib-worker-prod"
        mem_limit: 128m
        hostname: worker
        environment:
        - REDIS_HOST=$REDIS_HOST
        - REDIS_PORT=$REDIS_PORT
    nginx:
        image: "lmachraf/fib-nginx-prod"
        mem_limit: 128m
        hostname: nginx
        ports:
            - "80:80"