name: Deploy Project to Amazon Elastic Beanstalk

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            # Run the job only when the relevant files are changed
            - uses: dorny/paths-filter@v2
              id: filter
              with:
                filters: |
                  docker-config:
                    - 'docker-compose.yml'
                  app-code:
                    - 'client/**'
                    - 'server/**'
                    - 'nginx/**'
                    - 'worker/**'
            - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            - name: Build docker images
            # Build DEV test image
              run: docker build -t lmachraf/fib-test-dev -f ./client/Dockerfile.dev ./client
            # Build all PROD docker images individually
            - run: docker build -t lmachraf/fib-client-prod ./client
            - run: docker build -t lmachraf/fib-nginx-prod ./nginx
            - run: docker build -t lmachraf/fib-server-prod ./server
            - run: docker build -t lmachraf/fib-worker-prod ./worker
            # Push all images to Docker Hub
            - run: docker push lmachraf/fib-client-prod
            - run: docker push lmachraf/fib-nginx-prod
            - run: docker push lmachraf/fib-server-prod
            - run: docker push lmachraf/fib-worker-prod
            # Create a deployment package
            - name: Create deployment package
              run: zip -r deploy.zip . -x '*.git*'
    test:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/checkout@v2
            - run: docker run -e CI=true lmachraf/fib-test-dev npm test -- --coverage
    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            # Deploy to AWS EB
            - name: Deploy to Amazon Elastic Beanstalk
              uses: einaregilsson/beanstalk-deploy@v18
              with:
                aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
                aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
                application_name: fibonacci-iaac
                environment_name: Fibonacciiaac-env
                existing_bucket_name: elasticbeanstalk-eu-central-1-914580138132
                region: eu-central-1
                version_label: ${{ github.sha }}
                deployment_package: deploy.zip