name: Deploy Fib-IaaC to GKE
on:
  push:
    branches:
      - master

env:
  SHA: $(git rev-parse HEAD)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Tests
        run: |-
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD}}            
          docker build -t lmachraf/fib-test-dev -f ./client/Dockerfile.dev ./client
          docker run -e CI=true lmachraf/fib-test-dev npm test -- --coverage

      - name: Set GKE Service Key
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'
      
      - name: Setup the Project
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: fibonacci-iaac

      - name: Authenticate to Google Cloud
        run: |-
          gcloud --quiet auth configure-docker

      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: multi-cluster-fib-iaac
          location: europe-west1-c

      - name: Build Docker Images
        run: |-
          docker build -t lmachraf/fib-client-prod-k8s:latest -t lmachraf/fib-client-prod-k8s:${{ env.SHA }} -f ./client/Dockerfile ./client
          docker build -t lmachraf/fib-server-prod-k8s:latest -t lmachraf/fib-server-prod-k8s:${{ env.SHA }} -f ./server/Dockerfile ./server
          docker build -t lmachraf/fib-worker-prod-k8s:latest -t lmachraf/fib-worker-prod-k8s:${{ env.SHA }} -f ./server/Dockerfile ./server

      - name: Push to Docker Hub
        run: |-          
          docker push lmachraf/fib-client-prod-k8s:latest
          docker push lmachraf/fib-server-prod-k8s:latest
          docker push lmachraf/fib-worker-prod-k8s:latest
          docker push lmachraf/fib-client-prod-k8s:${{ env.SHA }}
          docker push lmachraf/fib-server-prod-k8s:${{ env.SHA }}
          docker push lmachraf/fib-worker-prod-k8s:${{ env.SHA }}

      - name: Apply Kubernetes Configurations
        run: |-
          kubectl apply -f ./kubernetes/client
          kubectl apply -f ./kubernetes/server
          kubectl apply -f ./kubernetes/worker
          kubectl apply -f ./kubernetes/postgres
          kubectl apply -f ./kubernetes/redis
          kubectl apply -f ./kubernetes/ingress
          kubectl set image deployments/server-deployment server=lmachraf/fib-server-prod-k8s:${{ env.SHA }}
          kubectl set image deployments/client-deployment client=lmachraf/fib-client-prod-k8s:${{ env.SHA }}
          kubectl set image deployments/worker-deployment worker=lmachraf/fib-worker-prod-k8s:${{ env.SHA }}