name: Deploy Project to Amazon Elastic Beanstalk

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            # Login to Docker
            - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            # Build DEV test image and run tests
            - run: docker build -t lmachraf/lmachraf -f ./client/Dockerfile.dev ./client
            - run: docker run -e CI=true lmachraf/react-test npm test -- --coverage
            # Build all PROD containers individually
            - run: docker build -t lmachraf/multi-client ./client
            - run: docker build -t lmachraf/multi-nginx ./nginx
            - run: docker build -t lmachraf/multi-server ./server
            - run: docker build -t lmachraf/multi-worker ./worker
            # Push containers to Docker Hub
            - run: docker push lmachraf/multi-client
            - run: docker push lmachraf/multi-nginx
            - run: docker push lmachraf/multi-server
            - run: docker push lmachraf/multi-worker
            # Create deployment package
            - name: Create deployment package
              run: zip -r deploy.zip . -x '*.git*'
            # Deploy to AWS EB
            # TODO