name: Deploy Project to Amazon Elastic Beanstalk

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            # Run the job only when the relevant files are changed
            - uses: dorny/paths-filter@v2
              id: filter
              with:
                filters: |
                  docker_config:
                    - 'docker-compose.yml'
                  app_code:
                    - 'client/**'
                    - 'server/**'
                    - 'nginx/**'
                    - 'worker/**'
            - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            - name: Build and publish all Docker images to DockerHub
              if: steps.filter.outputs.app_code == 'true' || steps.filter.outputs.docker_config == 'true'
              run: ${GITHUB_WORKSPACE}/.github/scripts/publish_docker_images.sh
            # Create a deployment package
            - name: Create a deployment package artifact
              run: zip -r ./artifacts/deploy.zip . -x '*.git*'
            - uses: actions/upload-artifact@v2
              with:
                name: deployment-package
                path: ./artifacts/
    test:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/checkout@v2
            - run: docker build -t lmachraf/fib-test-dev -f ./client/Dockerfile.dev ./client
            - run: docker run -e CI=true lmachraf/fib-test-dev npm test -- --coverage
    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            # Deploy to AWS EB
            - name: Retrieve deployment artifact from the build job
              uses: actions/download-artifact@v2
              with:
                name: deployment-package
                path: ./artifacts/
            - name: Deploy to Amazon Elastic Beanstalk
              uses: einaregilsson/beanstalk-deploy@v18
              with:
                aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
                aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
                application_name: fibonacci-iaac
                environment_name: Fibonacciiaac-env
                existing_bucket_name: elasticbeanstalk-eu-central-1-914580138132
                region: eu-central-1
                version_label: ${{ github.sha }}
                deployment_package: deploy.zip